GET http://localhost:4000/thesis/
###

POST http://localhost:4000/thesis/ HTTP/1.1
Content-Type: application/json

{
    "thesisId": "2021-3-2",
    "name": "Inteligencia artificial enfocada en automatas 2",
    "year": 2019,
    "tags": [
        "ia",
        "automatas",
        "web"
    ],
    "school": "Escuela Superior de Comedia",
    "synodals": [
        "Luis Resendiz",
        "Alfredo Pereda",
        "Joslay Cabrera"
    ],
    "director": "Juan Perez Perez",
    "authors": [
        "Author 1",
        "Author 2"
    ]
}

###
GET http://localhost:4000/thesis/search/?tags=ia